name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: 'package.json'

      - run: bun install --frozen-lockfile
      - run: bun lint

      - name: Build react-netlify-forms
        run: bun run build

      - name: Build docs
        run: bun run docs:build
        env:
          GATSBY_SITE_RECAPTCHA_KEY: ${{ secrets.GATSBY_SITE_RECAPTCHA_KEY }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/docs/dist
