name: publish github packages

on:
  release:
    types: [published]

jobs:
  publish-gpr:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: 'package.json'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@Pyrax'

      - run: bun install --frozen-lockfile

      - name: Autoscope package.json
        uses: khaazz/action-autoscope@master

      - run: bun publish --registry=https://npm.pkg.github.com/Pyrax --cwd ./packages/react-netlify-forms
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
