name: publish github packages

on:
  release:
    types: [published]

jobs:
  publish-gpr:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@Pyrax'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: yarn install --frozen-lockfile

      - name: Autoscope package.json
        uses: khaazz/action-autoscope@master

      - run: yarn publish --registry=https://npm.pkg.github.com/Pyrax
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
