name: publish github packages

on:
  release:
    types: [published]

jobs:
  publish-gpr:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@Pyrax'
          cache: 'yarn'

      - run: yarn install
      - name: Autoscope package.json
        uses: khaazz/action-autoscope@master

      - run: yarn publish --registry=https://npm.pkg.github.com/Pyrax
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
