name: release

on:
  push:
    branches:
      - master

permissions:
  contents: read # for checkout

jobs:
  semantic-release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: 'package.json'

      - run: bun install --frozen-lockfile
      - name: Check tests before release
        run: bun lint

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
